### ISSUE TITLE
[BUG] crashes on startup

### ISSUE THREAD

**Issue by sirdeggen** [libsv/pulse#94]
**Describe the bug**

**To Reproduce**
1. fresh droplet on digital ocean ubuntu smallest, docker pre-installed
2. docker compose up -d with this docker-compose.yaml below

```yaml
version: '3.8'

services:
  app:
    container_name: pulse
    build: ./
    ports:
      - "8080:8080"
      - "8333:8333"
    environment:
      - DB_PREPAREDDB=true
      - DB_PREPAREDDBFILE_PATH=./data/blockheaders.xz
    restart: unless-stopped
    volumes:
      - p2p-headers-data:/data
volumes:
  p2p-headers-data:
    external: false
```

**Expected behavior**
Load existing database and continue to receive new headers from the network.

**Screenshots & Logs**
It crashes with the  following log. Restarting resolves the issue:

```bash
2023-04-12 01:23:01.549 [INF] HEADERS: Reached the final checkpoint -- switching to normal mode
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa812b9]

goroutine 27 [running]:
github.com/libsv/bitcoin-hc/transports/p2p/p2psync.(*SyncManager).handleHeadersMsg(0xc00041cd20, 0xc000037460)
	/go/transports/p2p/p2psync/manager.go:600 +0xad9
github.com/libsv/bitcoin-hc/transports/p2p/p2psync.(*SyncManager).blockHandler(0xc00041cd20)
	/go/transports/p2p/p2psync/manager.go:756 +0x172
created by github.com/libsv/bitcoin-hc/transports/p2p/p2psync.(*SyncManager).Start
	/go/transports/p2p/p2psync/manager.go:851 +0xca
```

**System Information (please complete the following information):**

 - OS: Ubuntu
 - Go version: from the Dockerfile
- pulse version: v0.1.1

**Additional context**
